LOW_PRODUCT_INVENTORY_THRESHOLD = 1000

LOYALTY_POINTS_PER_20_DOLLARS = 10
LOYALTY_POINTS_CONVERSION_RATE = 100 # for 1$
TOTAL_LOYALTY_POINTS_FOR_VIP_STATUS = 1000

VIP_DISCOUNT_PERCENTAGE = 5
VIP_LOYALTY_POINTS_PER_20_DOLLARS = 25